services:
  postgres:
    image: postgres:16-alpine
    container_name: ashvault-db
    restart: always
    environment:
      POSTGRES_USER: ashvault
      POSTGRES_PASSWORD: a_sample_password
      POSTGRES_DB: ashvault
    ports:
      # Host 5432 -> container 5432. choose other host port if you already have a local postgres running on 5432,
      - '5432:5432'
    volumes:
      - ashvault-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ashvault -d ashvault']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  ashvault-pgdata:
